import type { ColumnDef } from "@tanstack/react-table";

type UserStatus = "active" | "inactive";

export type User = {
  id: string; // UUID
  user_id: string; // FK to users
  name: string;
  department: string;
  qualification: string;
  joining_date: string; // Date in ISO format (YYYY-MM-DD)
  status: UserStatus;
};

export const teachersData: User[] = [
  {
    id: "1",
    user_id: "user_1",
    name: "Ahmed Khan",
    department: "Quran",
    qualification: "Hafiz-ul-Quran, Ijazah in Qira'at",
    joining_date: "2020-01-15",
    status: "active",
  },
  {
    id: "2",
    user_id: "user_2",
    name: "Fatima Ali",
    department: "Fiqh",
    qualification: "Alimiyyah Degree, Specialization in Fiqh",
    joining_date: "2019-05-22",
    status: "active",
  },
  {
    id: "3",
    user_id: "user_3",
    name: "Yusuf Abdullah",
    department: "Hadeeth",
    qualification: "Masters in Hadith Sciences",
    joining_date: "2021-03-10",
    status: "active",
  },
  {
    id: "4",
    user_id: "user_4",
    name: "Aisha Mohammed",
    department: "Arabic",
    qualification: "PhD in Arabic Language and Literature",
    joining_date: "2018-11-05",
    status: "active",
  },
  {
    id: "5",
    user_id: "user_5",
    name: "Omar Farooq",
    department: "Islamic History",
    qualification: "MA in Islamic History and Civilization",
    joining_date: "2022-02-18",
    status: "active",
  },
  {
    id: "6",
    user_id: "user_6",
    name: "Maryam Ibrahim",
    department: "Quran",
    qualification: "Hafiza, Qaria with Ijazah in Hafs 'an 'Asim",
    joining_date: "2021-07-10",
    status: "active",
  },
  {
    id: "7",
    user_id: "user_7",
    name: "Khalid Hassan",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Hanafi Fiqh",
    joining_date: "2020-09-15",
    status: "active",
  },
  {
    id: "8",
    user_id: "user_8",
    name: "Zainab Ahmed",
    department: "Tajweed",
    qualification: "Ijazah in Tajweed and Qira'at",
    joining_date: "2021-01-10",
    status: "active",
  },
  {
    id: "9",
    user_id: "user_9",
    name: "Ibrahim Malik",
    department: "Islamic Finance",
    qualification: "PhD in Islamic Economics and Finance",
    joining_date: "2020-06-22",
    status: "active",
  },
  {
    id: "10",
    user_id: "user_10",
    name: "Amina Yusuf",
    department: "Quran Memorization",
    qualification: "Hafiza with Ijazah in Hafs and Shu'bah",
    joining_date: "2022-03-15",
    status: "active",
  },
  {
    id: "11",
    user_id: "user_11",
    name: "Mohammed Ali",
    department: "Seerah",
    qualification: "MA in Islamic Studies, Specialization in Seerah",
    joining_date: "2019-08-05",
    status: "inactive",
  },
  {
    id: "12",
    user_id: "user_12",
    name: "Sarah Johnson",
    department: "Islamic Psychology",
    qualification: "PhD in Psychology, Islamic Counseling Certification",
    joining_date: "2021-09-12",
    status: "active",
  },
  {
    id: "13",
    user_id: "user_13",
    name: "Abdul Rahman",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Shafi'i Fiqh",
    joining_date: "2020-04-18",
    status: "active",
  },
  {
    id: "14",
    user_id: "user_14",
    name: "Fatima Zahra",
    department: "Islamic Art",
    qualification: "MA in Islamic Art and Architecture",
    joining_date: "2022-01-25",
    status: "active",
  },
  {
    id: "15",
    user_id: "user_15",
    name: "Yasin Ahmed",
    department: "Quran",
    qualification: "Hafiz with Ijazah in Warsh 'an Nafi'",
    joining_date: "2021-05-30",
    status: "active",
  },
  {
    id: "16",
    user_id: "user_16",
    name: "Huda Mohammed",
    department: "Tafseer",
    qualification: "MA in Tafseer and Quranic Sciences",
    joining_date: "2019-11-14",
    status: "active",
  },
  {
    id: "17",
    user_id: "user_17",
    name: "Tariq Mahmood",
    department: "Islamic History",
    qualification: "PhD in Islamic Civilization",
    joining_date: "2020-07-22",
    status: "inactive",
  },
  {
    id: "18",
    user_id: "user_18",
    name: "Noor Fatima",
    department: "Arabic",
    qualification: "BA in Arabic Language, Teaching Certification",
    joining_date: "2022-04-05",
    status: "active",
  },
  {
    id: "19",
    user_id: "user_19",
    name: "Hamza Abdullah",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Maliki Fiqh",
    joining_date: "2021-02-18",
    status: "active",
  },
  {
    id: "20",
    user_id: "user_20",
    name: "Ayesha Rahman",
    department: "Quran",
    qualification: "Hafiza with Ijazah in Qalun 'an Nafi'",
    joining_date: "2020-10-30",
    status: "active",
  },
  {
    id: "21",
    user_id: "user_21",
    name: "Othman Ibrahim",
    department: "Islamic Finance",
    qualification: "MSc in Islamic Banking and Finance",
    joining_date: "2021-08-15",
    status: "active",
  },
  {
    id: "22",
    user_id: "user_22",
    name: "Sumayya Ahmed",
    department: "Tajweed",
    qualification: "Ijazah in Tajweed and Qira'at",
    joining_date: "2022-02-22",
    status: "active",
  },
  {
    id: "23",
    user_id: "user_23",
    name: "Bilal Hassan",
    department: "Hadith",
    qualification: "MA in Hadith Sciences",
    joining_date: "2020-03-17",
    status: "active",
  },
  {
    id: "24",
    user_id: "user_24",
    name: "Zahra Mohammed",
    department: "Islamic Psychology",
    qualification: "PhD in Clinical Psychology, Islamic Counseling",
    joining_date: "2021-11-05",
    status: "active",
  },
  {
    id: "25",
    user_id: "user_25",
    name: "Kareem Abdullah",
    department: "Seerah",
    qualification: "MA in Islamic Studies",
    joining_date: "2020-12-10",
    status: "inactive",
  },
  {
    id: "26",
    user_id: "user_26",
    name: "Mariam Khan",
    department: "Quran Memorization",
    qualification: "Hafiza with Ijazah in multiple Qira'at",
    joining_date: "2022-01-18",
    status: "active",
  },
  {
    id: "27",
    user_id: "user_27",
    name: "Idris Malik",
    department: "Islamic Finance",
    qualification: "PhD in Islamic Economics",
    joining_date: "2019-09-22",
    status: "active",
  },
  {
    id: "28",
    user_id: "user_28",
    name: "Amina Hassan",
    department: "Tafseer",
    qualification: "MA in Tafseer and Quranic Exegesis",
    joining_date: "2021-06-30",
    status: "active",
  },
  {
    id: "29",
    user_id: "user_29",
    name: "Yahya Ali",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Hanbali Fiqh",
    joining_date: "2020-08-14",
    status: "active",
  },
  {
    id: "30",
    user_id: "user_30",
    name: "Safiya Rahman",
    department: "Islamic Art",
    qualification: "BA in Fine Arts, Islamic Calligraphy",
    joining_date: "2022-03-08",
    status: "active",
  },
  {
    id: "31",
    user_id: "user_31",
    name: "Musa Ibrahim",
    department: "Quran",
    qualification: "Hafiz with Ijazah in Al-Duri 'an Abi Amr",
    joining_date: "2021-04-25",
    status: "active",
  },
  {
    id: "32",
    user_id: "user_32",
    name: "Aisha Abdullah",
    department: "Islamic History",
    qualification: "PhD in Islamic Civilization and History",
    joining_date: "2019-12-15",
    status: "active",
  },
];

export const columns: ColumnDef<User>[] = [
  {
    accessorKey: "id",
    header: "ID",
  },
  {
    accessorKey: "user_id",
    header: "User ID",
  },
  {
    accessorKey: "name",
    header: "Name",
  },
  {
    accessorKey: "department",
    header: "Department",
  },
  {
    accessorKey: "qualification",
    header: "Qualification",
  },
  {
    accessorKey: "joining_date",
    header: "Joining Date",
  },
  {
    accessorKey: "status",
    header: "Status",
  },
  // {
  //   accessorKey: "actions",
  //   header: "",
  // },
];
