import type { ColumnDef } from "@tanstack/react-table";

type UserStatus = "active" | "inactive" | "graduated";

export type User = {
  id: string; // UUID
  user_id: string; // FK to users
  name: string;
  department: string;
  qualification: string;
  joining_date: string; // Date in ISO format (YYYY-MM-DD)
  status: UserStatus;
};

export type Student = {
  id: string; // UUID
  admission_no: string; // Unique admission number
  first_name: string;
  last_name: string;
  gender: "male" | "female";
  dob: string; // Date of Birth in ISO format (YYYY-MM-DD)
  phone: string;
  guardian_name: string;
  address: string;
  admission_date: string; // Date in ISO format (YYYY-MM-DD)
  status: UserStatus;
  academic_year_id: string; // FK to academic_years
  department: string;
  qualification: string;
  joining_date: string; // Date in ISO format (YYYY-MM-DD)
};

export const teachersData: User[] = [
  {
    id: "1",
    user_id: "user_1",
    name: "Ahmed Khan",
    department: "Quran",
    qualification: "Hafiz-ul-Quran, Ijazah in Qira'at",
    joining_date: "2020-01-15",
    status: "active",
  },
  {
    id: "2",
    user_id: "user_2",
    name: "Fatima Ali",
    department: "Fiqh",
    qualification: "Alimiyyah Degree, Specialization in Fiqh",
    joining_date: "2019-05-22",
    status: "active",
  },
  {
    id: "3",
    user_id: "user_3",
    name: "Yusuf Abdullah",
    department: "Hadeeth",
    qualification: "Masters in Hadith Sciences",
    joining_date: "2021-03-10",
    status: "active",
  },
  {
    id: "4",
    user_id: "user_4",
    name: "Aisha Mohammed",
    department: "Arabic",
    qualification: "PhD in Arabic Language and Literature",
    joining_date: "2018-11-05",
    status: "active",
  },
  {
    id: "5",
    user_id: "user_5",
    name: "Omar Farooq",
    department: "Islamic History",
    qualification: "MA in Islamic History and Civilization",
    joining_date: "2022-02-18",
    status: "active",
  },
  {
    id: "6",
    user_id: "user_6",
    name: "Maryam Ibrahim",
    department: "Quran",
    qualification: "Hafiza, Qaria with Ijazah in Hafs 'an 'Asim",
    joining_date: "2021-07-10",
    status: "active",
  },
  {
    id: "7",
    user_id: "user_7",
    name: "Khalid Hassan",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Hanafi Fiqh",
    joining_date: "2020-09-15",
    status: "active",
  },
  {
    id: "8",
    user_id: "user_8",
    name: "Zainab Ahmed",
    department: "Tajweed",
    qualification: "Ijazah in Tajweed and Qira'at",
    joining_date: "2021-01-10",
    status: "active",
  },
  {
    id: "9",
    user_id: "user_9",
    name: "Ibrahim Malik",
    department: "Islamic Finance",
    qualification: "PhD in Islamic Economics and Finance",
    joining_date: "2020-06-22",
    status: "active",
  },
  {
    id: "10",
    user_id: "user_10",
    name: "Amina Yusuf",
    department: "Quran Memorization",
    qualification: "Hafiza with Ijazah in Hafs and Shu'bah",
    joining_date: "2022-03-15",
    status: "active",
  },
  {
    id: "11",
    user_id: "user_11",
    name: "Mohammed Ali",
    department: "Seerah",
    qualification: "MA in Islamic Studies, Specialization in Seerah",
    joining_date: "2019-08-05",
    status: "inactive",
  },
  {
    id: "12",
    user_id: "user_12",
    name: "Sarah Johnson",
    department: "Islamic Psychology",
    qualification: "PhD in Psychology, Islamic Counseling Certification",
    joining_date: "2021-09-12",
    status: "active",
  },
  {
    id: "13",
    user_id: "user_13",
    name: "Abdul Rahman",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Shafi'i Fiqh",
    joining_date: "2020-04-18",
    status: "active",
  },
  {
    id: "14",
    user_id: "user_14",
    name: "Fatima Zahra",
    department: "Islamic Art",
    qualification: "MA in Islamic Art and Architecture",
    joining_date: "2022-01-25",
    status: "active",
  },
  {
    id: "15",
    user_id: "user_15",
    name: "Yasin Ahmed",
    department: "Quran",
    qualification: "Hafiz with Ijazah in Warsh 'an Nafi'",
    joining_date: "2021-05-30",
    status: "active",
  },
  {
    id: "16",
    user_id: "user_16",
    name: "Huda Mohammed",
    department: "Tafseer",
    qualification: "MA in Tafseer and Quranic Sciences",
    joining_date: "2019-11-14",
    status: "active",
  },
  {
    id: "17",
    user_id: "user_17",
    name: "Tariq Mahmood",
    department: "Islamic History",
    qualification: "PhD in Islamic Civilization",
    joining_date: "2020-07-22",
    status: "inactive",
  },
  {
    id: "18",
    user_id: "user_18",
    name: "Noor Fatima",
    department: "Arabic",
    qualification: "BA in Arabic Language, Teaching Certification",
    joining_date: "2022-04-05",
    status: "active",
  },
  {
    id: "19",
    user_id: "user_19",
    name: "Hamza Abdullah",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Maliki Fiqh",
    joining_date: "2021-02-18",
    status: "active",
  },
  {
    id: "20",
    user_id: "user_20",
    name: "Ayesha Rahman",
    department: "Quran",
    qualification: "Hafiza with Ijazah in Qalun 'an Nafi'",
    joining_date: "2020-10-30",
    status: "active",
  },
  {
    id: "21",
    user_id: "user_21",
    name: "Othman Ibrahim",
    department: "Islamic Finance",
    qualification: "MSc in Islamic Banking and Finance",
    joining_date: "2021-08-15",
    status: "active",
  },
  {
    id: "22",
    user_id: "user_22",
    name: "Sumayya Ahmed",
    department: "Tajweed",
    qualification: "Ijazah in Tajweed and Qira'at",
    joining_date: "2022-02-22",
    status: "active",
  },
  {
    id: "23",
    user_id: "user_23",
    name: "Bilal Hassan",
    department: "Hadith",
    qualification: "MA in Hadith Sciences",
    joining_date: "2020-03-17",
    status: "active",
  },
  {
    id: "24",
    user_id: "user_24",
    name: "Zahra Mohammed",
    department: "Islamic Psychology",
    qualification: "PhD in Clinical Psychology, Islamic Counseling",
    joining_date: "2021-11-05",
    status: "active",
  },
  {
    id: "25",
    user_id: "user_25",
    name: "Kareem Abdullah",
    department: "Seerah",
    qualification: "MA in Islamic Studies",
    joining_date: "2020-12-10",
    status: "inactive",
  },
  {
    id: "26",
    user_id: "user_26",
    name: "Mariam Khan",
    department: "Quran Memorization",
    qualification: "Hafiza with Ijazah in multiple Qira'at",
    joining_date: "2022-01-18",
    status: "active",
  },
  {
    id: "27",
    user_id: "user_27",
    name: "Idris Malik",
    department: "Islamic Finance",
    qualification: "PhD in Islamic Economics",
    joining_date: "2019-09-22",
    status: "active",
  },
  {
    id: "28",
    user_id: "user_28",
    name: "Amina Hassan",
    department: "Tafseer",
    qualification: "MA in Tafseer and Quranic Exegesis",
    joining_date: "2021-06-30",
    status: "active",
  },
  {
    id: "29",
    user_id: "user_29",
    name: "Yahya Ali",
    department: "Fiqh",
    qualification: "Alim Course, Specialization in Hanbali Fiqh",
    joining_date: "2020-08-14",
    status: "active",
  },
  {
    id: "30",
    user_id: "user_30",
    name: "Safiya Rahman",
    department: "Islamic Art",
    qualification: "BA in Fine Arts, Islamic Calligraphy",
    joining_date: "2022-03-08",
    status: "active",
  },
  {
    id: "31",
    user_id: "user_31",
    name: "Musa Ibrahim",
    department: "Quran",
    qualification: "Hafiz with Ijazah in Al-Duri 'an Abi Amr",
    joining_date: "2021-04-25",
    status: "active",
  },
  {
    id: "32",
    user_id: "user_32",
    name: "Aisha Abdullah",
    department: "Islamic History",
    qualification: "PhD in Islamic Civilization and History",
    joining_date: "2019-12-15",
    status: "active",
  },
];

export const studentsData: Student[] = [
  {
    id: "1",
    admission_no: "STU2023001",
    first_name: "Mohammed",
    last_name: "Ahmed",
    gender: "male",
    dob: "2015-03-15",
    phone: "501234567",
    guardian_name: "Ahmed Mohammed",
    address: "123 Al Maktoum St, Dubai",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "2",
    admission_no: "STU2023002",
    first_name: "Fatima",
    last_name: "Ali",
    gender: "female",
    dob: "2016-05-22",
    phone: "551234567",
    guardian_name: "Ali Hassan",
    address: "456 Sheikh Zayed Rd, Dubai",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "3",
    admission_no: "STU2023003",
    first_name: "Omar",
    last_name: "Khalid",
    gender: "male",
    dob: "2015-11-10",
    phone: "521234567",
    guardian_name: "Khalid Omar",
    address: "789 Al Wasl Rd, Dubai",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "4",
    admission_no: "STU2023004",
    first_name: "Aisha",
    last_name: "Yusuf",
    gender: "female",
    dob: "2016-07-18",
    phone: "581234567",
    guardian_name: "Yusuf Ahmed",
    address: "321 Jumeirah St, Dubai",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "5",
    admission_no: "STU2022001",
    first_name: "Ahmed",
    last_name: "Ibrahim",
    gender: "male",
    dob: "2014-09-25",
    phone: "501234568",
    guardian_name: "Ibrahim Mohammed",
    address: "654 Al Barsha, Dubai",
    admission_date: "2022-09-01",
    status: "graduated",
    academic_year_id: "2",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2022-09-01",
  },
  {
    id: "6",
    admission_no: "STU2023006",
    first_name: "Mariam",
    last_name: "Omar",
    gender: "female",
    dob: "2016-09-05",
    phone: "561234567",
    guardian_name: "Omar Khalid",
    address: "987 Corniche Rd, Abu Dhabi",
    admission_date: "2023-09-01",
    status: "inactive",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "7",
    admission_no: "STU2023007",
    first_name: "Khalid",
    last_name: "Hassan",
    gender: "male",
    dob: "2015-12-12",
    phone: "571234567",
    guardian_name: "Hassan Ahmed",
    address: "159 Al Bateen St, Abu Dhabi",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "8",
    admission_no: "STU2023008",
    first_name: "Layla",
    last_name: "Mohammed",
    gender: "female",
    dob: "2016-03-30",
    phone: "591234567",
    guardian_name: "Mohammed Ali",
    address: "753 Al Nahyan St, Abu Dhabi",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "9",
    admission_no: "STU2023007",
    first_name: "Khalid",
    last_name: "Abdullah",
    gender: "male",
    dob: "2015-04-12",
    phone: "501234570",
    guardian_name: "Abdullah Khalid",
    address: "246 Al Barsha, Dubai",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "10",
    admission_no: "STU2023005",
    first_name: "Yusuf",
    last_name: "Ibrahim",
    gender: "male",
    dob: "2015-02-25",
    phone: "541234567",
    guardian_name: "Ibrahim Ali",
    address: "654 Al Falah St, Abu Dhabi",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "11",
    admission_no: "STU2023011",
    first_name: "Abdullah",
    last_name: "Mohammed",
    gender: "male",
    dob: "2015-06-18",
    phone: "551234568",
    guardian_name: "Mohammed Ali",
    address: "111 Al Karama, Dubai",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "12",
    admission_no: "STU2023012",
    first_name: "Amina",
    last_name: "Omar",
    gender: "female",
    dob: "2016-01-22",
    phone: "521234568",
    guardian_name: "Omar Khalid",
    address: "222 Al Qusais, Dubai",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "13",
    admission_no: "STU2023013",
    first_name: "Ibrahim",
    last_name: "Yousef",
    gender: "male",
    dob: "2015-08-14",
    phone: "581234568",
    guardian_name: "Yousef Ahmed",
    address: "333 Al Nahda, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "14",
    admission_no: "STU2023014",
    first_name: "Zainab",
    last_name: "Khalid",
    gender: "female",
    dob: "2016-04-30",
    phone: "561234568",
    guardian_name: "Khalid Omar",
    address: "444 Al Majaz, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "15",
    admission_no: "STU2023015",
    first_name: "Omar",
    last_name: "Ahmed",
    gender: "male",
    dob: "2015-11-05",
    phone: "501234571",
    guardian_name: "Ahmed Ali",
    address: "555 Al Qasba, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "16",
    admission_no: "STU2023016",
    first_name: "Huda",
    last_name: "Mohammed",
    gender: "female",
    dob: "2016-07-12",
    phone: "551234569",
    guardian_name: "Mohammed Hassan",
    address: "666 Al Khan, Ajman",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "17",
    admission_no: "STU2023017",
    first_name: "Yousef",
    last_name: "Abdul",
    gender: "male",
    dob: "2015-09-23",
    phone: "521234569",
    guardian_name: "Abdul Rahman",
    address: "777 Al Jurf, Ajman",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "18",
    admission_no: "STU2023018",
    first_name: "Layla",
    last_name: "Kareem",
    gender: "female",
    dob: "2016-02-17",
    phone: "581234569",
    guardian_name: "Kareem Ahmed",
    address: "888 Al Hamra, Ras Al Khaimah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "19",
    admission_no: "STU2023019",
    first_name: "Khalid",
    last_name: "Nasser",
    gender: "male",
    dob: "2015-12-08",
    phone: "561234569",
    guardian_name: "Nasser Ali",
    address: "999 Al Dhaid, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "20",
    admission_no: "STU2023020",
    first_name: "Aisha",
    last_name: "Tariq",
    gender: "female",
    dob: "2016-06-19",
    phone: "501234572",
    guardian_name: "Tariq Mohammed",
    address: "1010 Al Qusaidat, Fujairah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "21",
    admission_no: "STU2023021",
    first_name: "Mohammed",
    last_name: "Saif",
    gender: "male",
    dob: "2015-10-11",
    phone: "551234570",
    guardian_name: "Saif Ahmed",
    address: "1111 Al Aqah, Fujairah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "22",
    admission_no: "STU2023022",
    first_name: "Fatima",
    last_name: "Majid",
    gender: "female",
    dob: "2016-03-25",
    phone: "521234570",
    guardian_name: "Majid Omar",
    address: "1212 Al Madam, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "23",
    admission_no: "STU2023023",
    first_name: "Omar",
    last_name: "Faisal",
    gender: "male",
    dob: "2015-07-16",
    phone: "581234570",
    guardian_name: "Faisal Khalid",
    address: "1313 Al Dhaid Road, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "24",
    admission_no: "STU2023024",
    first_name: "Mariam",
    last_name: "Waleed",
    gender: "female",
    dob: "2016-01-09",
    phone: "561234570",
    guardian_name: "Waleed Ali",
    address: "1414 Al Qasimia, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "25",
    admission_no: "STU2023025",
    first_name: "Ahmed",
    last_name: "Hamad",
    gender: "male",
    dob: "2015-05-27",
    phone: "501234573",
    guardian_name: "Hamad Khalifa",
    address: "1515 Al Taawun, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "26",
    admission_no: "STU2023026",
    first_name: "Aisha",
    last_name: "Sultan",
    gender: "female",
    dob: "2016-08-14",
    phone: "551234571",
    guardian_name: "Sultan Mohammed",
    address: "1616 Al Majaz, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "27",
    admission_no: "STU2023027",
    first_name: "Khalid",
    last_name: "Rashid",
    gender: "male",
    dob: "2015-11-30",
    phone: "521234571",
    guardian_name: "Rashid Ahmed",
    address: "1717 Al Khan, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "28",
    admission_no: "STU2023028",
    first_name: "Noor",
    last_name: "Hassan",
    gender: "female",
    dob: "2016-05-22",
    phone: "581234571",
    guardian_name: "Hassan Ali",
    address: "1818 Al Nahda, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  },
  {
    id: "29",
    admission_no: "STU2023029",
    first_name: "Yousef",
    last_name: "Ibrahim",
    gender: "male",
    dob: "2015-09-03",
    phone: "561234571",
    guardian_name: "Ibrahim Khalid",
    address: "1919 Al Qasba, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Quran",
    qualification: "Hafiz",
    joining_date: "2023-09-01",
  },
  {
    id: "30",
    admission_no: "STU2023030",
    first_name: "Sarah",
    last_name: "Omar",
    gender: "female",
    dob: "2016-02-28",
    phone: "501234574",
    guardian_name: "Omar Nasser",
    address: "2020 Al Majaz, Sharjah",
    admission_date: "2023-09-01",
    status: "active",
    academic_year_id: "1",
    department: "Islamic Studies",
    qualification: "Student",
    joining_date: "2023-09-01",
  }
];

export const columns: ColumnDef<User>[] = [
  {
    accessorKey: "id",
    header: "ID",
  },
  {
    accessorKey: "user_id",
    header: "User ID",
  },
  {
    accessorKey: "name",
    header: "Name",
  },
  {
    accessorKey: "department",
    header: "Department",
  },
  {
    accessorKey: "qualification",
    header: "Qualification",
  },
  {
    accessorKey: "joining_date",
    header: "Joining Date",
  },
  {
    accessorKey: "status",
    header: "Status",
  },
  // {
  //   accessorKey: "actions",
  //   header: "",
  // },
];

export const studentColumns: ColumnDef<Student>[] = [
  {
    accessorKey: "admission_no",
    header: "Admission No",
  },
  {
    id: "name",
    header: "Name",
    cell: ({ row }) => {
      return `${row.original.first_name} ${row.original.last_name}`;
    },
  },
  {
    accessorKey: "phone",
    header: "Phone",
  },
  {
    accessorKey: "guardian_name",
    header: "Guardian Name",
  },
  {
    accessorKey: "joining_date",
    header: "Joining Date",
    cell: ({ row }) => {
      return new Date(row.original.joining_date).toLocaleDateString();
    },
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => {
      return row.original.status.charAt(0).toUpperCase() + row.original.status.slice(1);
    },
  },
];